CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id INT GENERATED BY DEFAULT AS IDENTITY,
    mpa_name varchar,
    CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
    );

CREATE TABLE IF NOT EXISTS films
(
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50),
    description varchar(200),
    release_date date,
    duration INT,
    mpa_id INT NOT NULL ,
    CONSTRAINT films_pk PRIMARY KEY (film_id)

    );
CREATE TABLE IF NOT EXISTS genre
(
    genre_id INT GENERATED BY DEFAULT AS IDENTITY,
    genre_name varchar,
    CONSTRAINT genre_pk PRIMARY KEY (genre_id)
);
CREATE TABLE IF NOT EXISTS film_genre
(
    film_id BIGINT ,
    genre_id INT
);

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR (30),
    email VARCHAR (30),
    name VARCHAR (30),
    birthday date,
    CONSTRAINT users_pk PRIMARY KEY (user_id)
);
CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT,
    user_id BIGINT
);
CREATE TABLE IF NOT EXISTS friends
(
    user_id BIGINT,
    friend_id BIGINT
);




