
CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id INT GENERATED BY DEFAULT AS IDENTITY,
    mpa_name varchar UNIQUE,
    CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
    );

CREATE TABLE IF NOT EXISTS films
(
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    description varchar(200),
    release_date date,
    duration INT,
    mpa_id INT REFERENCES mpa (mpa_id),
    CONSTRAINT films_pk PRIMARY KEY (film_id)

    );
CREATE TABLE IF NOT EXISTS genre
(
    genre_id INT,
    genre_name varchar UNIQUE,
    CONSTRAINT genre_pk PRIMARY KEY (genre_id)
);
CREATE TABLE IF NOT EXISTS film_genre
(
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INT REFERENCES genre (genre_id),
    CONSTRAINT film_genre_pk PRIMARY KEY(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR (30) NOT NULL UNIQUE,
    email VARCHAR (30) NOT NULL,
    name VARCHAR (30),
    birthday date,
    CONSTRAINT users_pk PRIMARY KEY (user_id)
);
CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE ,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT likes_pk PRIMARY KEY (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS friends
(
    user_id BIGINT REFERENCES users (user_id),
    friend_id BIGINT REFERENCES users (user_id),
    CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id)
);




